  name: test manual run
  on: push
  jobs:
    printHello:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'Hello Bhargav'
          name: printing
        - name: checkout
          uses: actions/checkout@v4
        - name: "install node"
          uses: actions/setup-node@v3
          with:
           node-version: 20.9.0
        - name: Install dependencies
          run: npm ci
        - name: run build
          run: npm run build

